import csv
import os

# --- CONFIGURATION ---
# This must be the file generated by generate_rates_v3.py (the one with ~2002 rows and correct rates)
INPUT_FILE = 'GLOBAL_COST_RATES_FINAL.csv'
OUTPUT_FILE = 'GLOBAL_COST_RATES_ENRICHED_FINAL.csv'

PRICE_TO_COST_MULTIPLIER = 2.35 

# Banding Logic (Hourly Rate Ranges in GBP)
BAND_RANGES = [
    (0, 65, 'J'),
    (65, 85, 'K'),
    (85, 105, 'L'),
    (105, 140, 'M'),
    (140, 200, 'N'),
    (200, 9999, 'O')
]

# Location Proxies
# If rate is 0/missing for Key, look up Value['base']. New Rate = Base Rate * Value['mult']
LOCATION_PROXIES = {
    'US-SEA': {'base': 'US-NYC', 'mult': 0.95}, 
    'US-AUS': {'base': 'US-NYC', 'mult': 0.85},
    'EU-ES':  {'base': 'UK-LON', 'mult': 0.75}, 
    'APAC-PH':{'base': 'APAC-IN', 'mult': 1.10},
}

def clean_currency(val):
    if not val: return 0.0
    clean = str(val).replace('£', '').replace('$', '').replace('€', '').replace(',', '').strip()
    try:
        return float(clean)
    except:
        return 0.0

def get_band_from_rate(rate):
    for low, high, band in BAND_RANGES:
        if low < rate <= high:
            return band
    return 'Unknown'

def refine_data():
    print("--- Starting Data Refinement (v6) ---")
    
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Could not find {INPUT_FILE}")
        return

    rows = []
    
    # 1. READ DATA
    # Use utf-8-sig to handle BOM if present
    with open(INPUT_FILE, mode='r', encoding='utf-8-sig', errors='replace') as f:
        reader = csv.DictReader(f)
        input_fieldnames = reader.fieldnames
        if not input_fieldnames:
            print("Error: Input file is empty or has no headers.")
            return
            
        for row in reader:
            rows.append(row)

    print(f"Loaded {len(rows)} rows.")

    # 2. BUILD LOOKUP MAP (Role|Region -> Rate)
    # Needed for finding proxy base rates (e.g. looking up UK-LON to calculate EU-ES)
    rate_lookup = {}
    for r in rows:
        role = r.get('Role', '').strip()
        region = r.get('Region', '').strip()
        rate = clean_currency(r.get('Rate_low', 0))
        if rate > 0:
            key = f"{role}|{region}"
            rate_lookup[key] = rate

    # 3. DEFINE OUTPUT HEADERS
    # Start with standard headers to ensure order
    standard_headers = ['Category | Function', 'Role', 'Resource type', 'Unit', 'Region', 'Rate_low', 'Rate_high', 'Currency', 'Source', 'Notes']
    new_headers = ['Estimated_Cost', 'Band', 'Anomaly_Flag']
    
    # Combine, ensuring no duplicates
    final_headers = list(standard_headers)
    for h in new_headers:
        if h not in final_headers:
            final_headers.append(h)

    # 4. PROCESS ROWS
    enriched_rows = []
    count_proxies = 0
    
    for row in rows:
        # Create a new dict for the output row to ensure clean structure
        new_row = {k: row.get(k, '') for k in standard_headers}
        
        role = new_row['Role']
        region = new_row['Region']
        rate_low = clean_currency(new_row['Rate_low'])
        
        notes = new_row['Notes']
        anomaly = ""

        # A. FILL GAPS WITH PROXIES
        if rate_low == 0 and region in LOCATION_PROXIES:
            proxy = LOCATION_PROXIES[region]
            base_region = proxy['base']
            base_key = f"{role}|{base_region}"
            
            if base_key in rate_lookup:
                base_rate = rate_lookup[base_key]
                new_rate = round(base_rate * proxy['mult'], 2)
                
                # Update the row
                new_row['Rate_low'] = new_rate
                new_row['Rate_high'] = new_rate # Assume single rate
                rate_low = new_rate # Update local var
                
                notes = f"{notes} | Proxy: {base_region} x {proxy['mult']}"
                count_proxies += 1
            else:
                 notes = f"{notes} | Missing Base: {base_region}"

        # B. CALCULATE COST
        if rate_low > 0:
            estimated_cost = round(rate_low / PRICE_TO_COST_MULTIPLIER, 2)
        else:
            estimated_cost = 0
        new_row['Estimated_Cost'] = estimated_cost

        # C. AUTO-BANDING
        if rate_low > 0:
            new_row['Band'] = get_band_from_rate(rate_low)
        else:
            new_row['Band'] = 'Unknown'

        # D. ANOMALY DETECTION
        if estimated_cost > rate_low and rate_low > 0:
            anomaly = "Cost > Price"
        
        new_row['Notes'] = notes.strip(' |')
        new_row['Anomaly_Flag'] = anomaly
        
        enriched_rows.append(new_row)

    # 5. WRITE OUTPUT
    try:
        with open(OUTPUT_FILE, mode='w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=final_headers)
            writer.writeheader()
            writer.writerows(enriched_rows)
        print(f"--- SUCCESS ---")
        print(f"Generated: {OUTPUT_FILE}")
        print(f"Total Rows: {len(enriched_rows)}")
        print(f"Filled {count_proxies} gaps using proxies.")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    refine_data()